export const STORAGE_KEYS = {
  USER: 'vonk:v1:profile',
  ROLE: 'vonk:v1:role',
  TOURNAMENTS: 'vonk:v1:tournaments',
  REGISTRATIONS: 'vonk:v1:registrations',
  TEAMS: 'vonk:v1:teams',
  WALLET: 'vonk:v1:wallet',
  TRANSACTIONS: 'vonk:v1:transactions',
  NOTIFICATIONS: 'vonk:v1:notifications',
  DISPUTES: 'vonk:v1:disputes',
  RESULTS: 'vonk:v1:results',
  SETTINGS: 'vonk:v1:settings',
  PLAYER_STATS: 'vonk:v1:player-stats',
  MATCH_HISTORY: 'vonk:v1:match-history',
  ACHIEVEMENTS: 'vonk:v1:achievements',
  FAVORITES: 'vonk:v1:favorites',
  TEAM_INVITATIONS: 'vonk:v1:team-invitations',
  TEAM_JOIN_REQUESTS: 'vonk:v1:team-join-requests',
  TEAM_ACTIVITIES: 'vonk:v1:team-activities',
  MATCH_RESULTS: 'vonk:v1:match-results',
  TOURNAMENT_STANDINGS: 'vonk:v1:tournament-standings',
  RESULT_PENALTIES: 'vonk:v1:result-penalties',
  RESULT_BONUSES: 'vonk:v1:result-bonuses',
  MVP_RECORDS: 'vonk:v1:mvp-records',
  RESULT_DISPUTES: 'vonk:v1:result-disputes',
  RESULT_REVISIONS: 'vonk:v1:result-revisions',
  SCORING_CONFIGURATIONS: 'vonk:v1:scoring-configurations',
  ORGANIZERS: 'vonk:v1:organizers',
  ORGANIZER_SETTINGS: 'vonk:v1:organizer-settings',
  ORGANIZER_ACTIVITIES: 'vonk:v1:organizer-activities',
  ORGANIZER_ANNOUNCEMENTS: 'vonk:v1:organizer-announcements',
  PRIZE_DISTRIBUTIONS: 'vonk:v1:prize-distributions',
  ORGANIZER_ANALYTICS_CACHE: 'vonk:v1:organizer-analytics-cache',
  ADMINS: 'vonk:v1:admins',
  ADMIN_SETTINGS: 'vonk:v1:admin-settings',
  AUDIT_LOGS: 'vonk:v1:audit-logs',
  REPORTS: 'vonk:v1:reports',
  PLATFORM_ANNOUNCEMENTS: 'vonk:v1:platform-announcements',
  ADMIN_ANNOUNCEMENTS: 'vonk:v1:admin-announcements',
  ADMIN_ANALYTICS: 'vonk:v1:admin-analytics',
  NOTIFICATION_PREFERENCES: 'vonk:v1:notification-preferences',
  NOTIFICATION_EVENT_KEYS: 'vonk:v1:notification-event-keys',
  SUPPORT_TICKETS: 'vonk:v1:support-tickets',
  SUPPORT_MESSAGES: 'vonk:v1:support-messages',
  HELP_RECENTLY_VIEWED: 'vonk:v1:help-recently-viewed',
  ISSUE_REPORTS: 'vonk:v1:issue-reports',
  PLATFORM_STATUS: 'vonk:v1:platform-status',
  USER_SETTINGS: 'vonk:v1:user-settings',
  DATA_MANAGEMENT_HISTORY: 'vonk:v1:data-management-history',
  DEMO_ROLE: 'vonk:v1:demo-role',
  ONBOARDING_STATE: 'vonk:v1:onboarding-state',
  RECENT_SEARCHES: 'vonk:v1:recent-searches',
  STORAGE_SCHEMA: 'vonk:v1:storage-schema',
  STORAGE_MIGRATIONS: 'vonk:v1:storage-migrations',
  STORAGE_BACKUPS: 'vonk:v1:storage-backups',
  DATA_INTEGRITY_HISTORY: 'vonk:v1:data-integrity-history',
  READINESS_SUMMARY: 'vonk:v1:readiness-summary',
};

export const ROUTES = {
  HOME: '/',
  SEARCH: '/search',
  TOURNAMENTS: '/tournaments',
  MY_TOURNAMENTS: '/my-tournaments',
  TEAMS: '/teams',
  WALLET: '/wallet',
  TRANSACTIONS: '/wallet/transactions',
  LEADERBOARD: '/leaderboard',
  RANKINGS: '/rankings',
  ACHIEVEMENTS: '/achievements',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  SUPPORT: '/support',
  SUPPORT_TICKETS: '/support/tickets',
  SUPPORT_TICKET_NEW: '/support/tickets/new',
  SUPPORT_REPORT: '/support/report',
  SUPPORT_STATUS: '/support/status',
  HELP: '/help',
  RULES: '/rules',
  TERMS: '/terms',
  SETTINGS: '/settings',
  SETTINGS_APPEARANCE: '/settings/appearance',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_PRIVACY: '/settings/privacy',
  SETTINGS_ACCESSIBILITY: '/settings/accessibility',
  SETTINGS_LANGUAGE_REGION: '/settings/language-region',
  SETTINGS_GAMEPLAY: '/settings/gameplay',
  SETTINGS_DATA: '/settings/data',
  SETTINGS_ABOUT: '/settings/about',
  SETTINGS_READINESS: '/settings/readiness',
  ORGANIZER: '/organizer',
  ORGANIZER_TOURNAMENTS: '/organizer/tournaments',
  ORGANIZER_CREATE: '/organizer/tournaments/create',
  ADMIN: '/admin',
  ADMIN_PLAYERS: '/admin/players',
  ADMIN_TEAMS: '/admin/teams',
  ADMIN_ORGANIZERS: '/admin/organizers',
  ADMIN_TOURNAMENTS: '/admin/tournaments',
  ADMIN_REGISTRATIONS: '/admin/registrations',
  ADMIN_MATCHES: '/admin/matches',
  ADMIN_RESULTS: '/admin/results',
  ADMIN_WALLETS: '/admin/wallets',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_DISPUTES: '/admin/disputes',
  ADMIN_ANNOUNCEMENTS: '/admin/announcements',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_SETTINGS: '/admin/settings',
};

export const LEGAL_DISCLAIMER =
  'VONK Tournaments is an independently operated tournament-management platform and is not affiliated with, endorsed by, or sponsored by KRAFTON, BGMI, Garena, or Free Fire. The current frontend demonstration does not process real payments. Wallet balances, entry fees, prizes, refunds and payouts are simulated.';

export const TOURNAMENT_MODES = [
  'Solo',
  'Duo',
  'Squad',
  'TDM 1v1',
  'TDM 2v2',
  'TDM 4v4',
  'Clan Battle',
  'Custom Room',
  'Sniper Only',
  'Pistol Only',
  'Melee Only',
  'College Tournament',
  'Invitational',
  'Practice Scrim',
  'Championship',
] as const;

export const TOURNAMENT_LEVELS = [
  'Beginner',
  'Intermediate',
  'Advanced',
  'Pro',
  'Invitational',
  'Championship',
] as const;

export const BGMI_MAPS = [
  'Erangel',
  'Miramar',
  'Sanhok',
  'Vikendi',
  'Nusa',
  'Karakin',
  'Livik',
  'Arena',
] as const;

export const DEFAULT_SCORING = {
  pointsPerKill: 1,
  placementPoints: {
    1: 10,
    2: 6,
    3: 5,
    4: 4,
    5: 3,
    6: 2,
    7: 2,
    8: 1,
    9: 1,
    10: 1,
  },
};

export const DEFAULT_RULES = [
  'Teaming with opponents will result in immediate disqualification and a ban from the platform.',
  'Usage of any hacks, third-party software, screen stretchers, or emulators is strictly prohibited.',
  'All players must record their gameplay or take screenshots of match results for dispute resolutions.',
  'Registered characters must match the exact In-Game Name (IGN) and Character ID in the profile.',
  'Room credentials will be released exactly 15 minutes before the match start time.',
  'Late entries will not be accommodated under any circumstances. Ensure you join your assigned slot.',
];
